name: CI Workflow

# trigger
on:
  push:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    name: "Build"
    uses: ./.github/workflows/build.yaml
    with:
      version: "8.2"

  test:
    name: "Test"
    needs: [build]
    uses: ./.github/workflows/test.yaml

  sonarcloud:
    name: "Sonar Cloud Scan"
    needs: [build]
    uses: ./.github/workflows/sonarcloud.yaml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
      SONAR_ORG: ${{ secrets.SONAR_ORG }}

  trivy-fs-scan: 
    name: "Trivy File Scan"
    uses: ./.github/workflows/trivy-file-scan.yaml

  docker-build-push:
    name: "Docker Build and Push"
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: zen1710/kv-app-laravel:v1.0

  
