name : "Main Workflow"

on : 
  pull_request : 
    branches : 
      - dev

jobs: 
  build: 
    name: "Build Laravel App"
    runs-on: ubuntu-latest 
    steps: 
      - name : Hello
        run: |
          echo "Hello"
