name: QA Workflow

# trigger
on:
  push:
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest
    steps:
      - name: Directory path
        run: |
          pwd
          
      - name: Checkout
        uses: actions/checkout@v4

      -name: Build Laravel App
        runs-on: ubuntu-latest
        uses: ./.github/workflows/build.yml
        with:
          php-version: "8.3"

  test:
    name: Test the Application
    runs-on: ubuntu-latest
    needs: [build]
    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USERNAME: root
          MYSQL_DATABASE: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Laravel App
        uses: ./.github/actions/test