name: Sonar Cloud

on: 
  workflow_call:
    secrets:
      SONAR_TOKEN:
        required: true
      SONAR_PROJECT_KEY:
        required: true
      SONAR_ORG:
        required: true

jobs:
  sonar_cloud: 
    name: Sonar Cloud Scan
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2.1.0
        with:
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORG }}
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}