name: Test Workflow

on: workflow_call

jobs:
  test:
    name: Test the Application
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USERNAME: testing-user
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Restore the Cache
        id: cache
        uses: actions/cache@v4.0.2
        with:
          path: ./vendor
          key: ${{ github.sha }}-php-vendor-cache

      - name: Composer Install
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          composer install

      - name: Create .env
        run: |
          cp .env.ci .env

      - name: Generate the key
        run: |
          php artisan key:generate

      - name: Migrate the Database
        run: |
          php artisan migrate

      - name: Run Unit Testing
        run: |
          php artisan test